language: csharp
dotnet: 6.0
mono: none

before_install:
- export JUKTEMP=$(curl "https://api.github.com/repos/JukaLang/juka/releases/latest" | jq -r ".tag_name")

script:
  - sudo apt-get update
  - sudo apt-get install python3
  - export EMSDK_PYTHON=/usr/bin/python3 
  - sudo dotnet workload install wasm-tools
  - sudo dotnet add package JukaCompiler
  - sudo dotnet publish -c Release

before_deploy:
  - export TRAVIS_TAG=${JUKTEMP}
  - tar -zcf Juka_WebAssembly_${TRAVIS_TAG}.tar.gz -C bin/Release/net6.0/publish/ wwwroot
  - git tag $TRAVIS_TAG


deploy:
  provider: releases
  token:
    secure: "qfkKxi/yYs7dMuRm+GMMX3V9rTPednSVlB20+KJz8m4Clwkluk2ELcFlQ7697TWO32HksUBWc+HBeDaNoaCrywf0ouuJtIPXCqDWtlEqCsvxiGvrc9OgQKDcTj430IYodLQxSvDiHgMiAWzwWeQzk4tVkxV7xhCj0+JCjNk+GqpwcF6hze/64dNv95/zyS8eFLJticiE8m/lB83G0QCsNk/YXEN0Q2qHfE3xwUWuZ+C2cov5pZIBFmeAoAJhqqkJVJNXTur2l8E27WUnz+g0YYSSqvL2+GbS+JAP5XgI40o19QjmnJlUfmO0imsAnQXxAQxMUVmogfTT6DjPqJw7tSPD8ESyrWWMnkovIzeK5yqhEWzokXQGVCt2HVGAaiOGkecVDFFvQemarZojE/qRSbFkdkN4y0niX820aftdm7ZwbCxr+bKZ5tozPbzMVTYRb8wOTwVg+bklmQ76/6k0k9oYxEenHxHzkmGHkxmv3Fofn2cOrtnU7AVKd/WxAdy6eoeAUilZEq1ULgWLNTtKtcVEQv8MUCrX6RO+H/piRogFm2003FPLZLKd1vJ8a5pMOR7XRwH0/m3tXaQrpGhsnFp/Gei4DeLEGozwISJQ+ga4RiSIPSyIC6P/ASqAs751d0a++OX8mWPIDavY3ppmcXZ0RbFAM5l8L7BVOAL7fZs="
  file_glob: true
  file: Juka_WebAssembly_${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
    tags: false