image: Visual Studio 2022

branches:
  # whitelist
  only:
    - main

skip_tags: false
skip_non_tags: false

install:
  - ps: $env:package_version = (Invoke-WebRequest -URI "https://api.github.com/repos/JukaLang/juka/releases/latest" | ConvertFrom-Json).tag_name
  - ps: Update-AppveyorBuild -Version "$env:package_version"

dotnet_csproj:
  patch: true
  file: 'JukaWebAssembly.csproj'
  version: '{$env:package_version}'
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: '$env:package_version'
  file_version: '$env:package_version'
  informational_version: '$env:package_version'


build_script:
  - dotnet workload install wasm-tools JukaWebAssembly.sln
  - dotnet add package JukaCompiler JukaWebAssembly.sln
  - dotnet publish -c Release JukaWebAssembly.sln
  - git tag $env:package_version


configuration: Release

artifacts:
- path: 'src\Juka\bin\Release\net6.0\publish\wwwroot'
  name: Juka_WebAssembly_$env:package_version
  type: zip



deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/
    auth_token:
      secure: XCqLJKrsMnRCCEEcsPL53Emba/2GrP172INtXx86eu5XBbed614ug/2dcx8MZwmr
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only