image: Visual Studio 2022

branches:
  # whitelist
  only:
    - main

skip_tags: true
skip_non_tags: false

install:
  - ps: $env:package_version = (Invoke-WebRequest -URI "https://api.github.com/repos/JukaLang/juka/releases/latest" | ConvertFrom-Json).tag_name
  - ps: Update-AppveyorBuild -Version "$env:package_version - $($env:APPVEYOR_BUILD_VERSION)"
  - ps: Update-AppveyorBuild -Version "$env:package_version"

dotnet_csproj:
  patch: true
  file: 'JukaWebAssembly.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)


build_script:
  - ps: |
        $env:MY_XT=""
        if ($env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
        {
        $env:MY_XT="\n $($env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)"
        }
  - dotnet workload install wasm-tools
  - dotnet add package JukaCompiler
  - dotnet publish -c Release JukaWebAssembly.sln



configuration: Release

artifacts:
- path: 'bin\Release\net6.0\publish\wwwroot'
  name: Juka_WebAssembly_$(APPVEYOR_BUILD_VERSION)
  type: zip



deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/
    tag: '$(APPVEYOR_BUILD_VERSION)'
    release: 'JukaWASM v$(APPVEYOR_BUILD_VERSION)'
    description: '## 🍂 Changelog \n $(APPVEYOR_REPO_COMMIT_MESSAGE) $($env:MY_XT)'
    auth_token:
      secure: XCqLJKrsMnRCCEEcsPL53Emba/2GrP172INtXx86eu5XBbed614ug/2dcx8MZwmr
    draft: false
    prerelease: false
    on:
      branch: main                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only