image: Visual Studio 2022

branches:
  # whitelist
  only:
    - main

skip_tags: true
skip_non_tags: false

version: '{build}'

install:
  - ps: $env:package_version = (Invoke-WebRequest -URI "https://api.github.com/repos/JukaLang/juka/releases/latest" | ConvertFrom-Json).tag_name
  - ps: $env:changelog = (Invoke-WebRequest -URI "https://api.github.com/repos/JukaLang/juka/releases/latest" -UseBasicParsing | ConvertFrom-Json).body.Split([Environment]::NewLine) | Select -Skip 1 | Out-String
  - ps: Update-AppveyorBuild -Version "$env:package_version"

dotnet_csproj:
  patch: true
  file: 'JukaIDE.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)


build_script:
  - ps: |
        $env:MY_XT= "$($env:APPVEYOR_REPO_COMMIT_MESSAGE)"
        $env:MY_AV= $env:APPVEYOR_BUILD_VERSION
        if ($env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
        {
        $env:MY_XT= "$($env:APPVEYOR_REPO_COMMIT_MESSAGE) \n $($env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)"
        }
        if ($env:APPVEYOR_BUILD_VERSION -notlike "0.*")
        {
        $env:MY_AV="$($env:package_version)-Nightly-$($env:APPVEYOR_BUILD_VERSION)"
        }
  - dotnet workload install wasm-tools
  - dotnet add package JukaCompiler
  - dotnet publish -c Release JukaIDE.sln



configuration: Release

artifacts:
- path: 'bin\Release\net8.0\publish\wwwroot'
  name: Juka_IDE_$(APPVEYOR_BUILD_VERSION)
  type: zip

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.zip/
    tag: "$(MY_AV)"
    release: "📦 Juka IDE v$(MY_AV)"
    description: "## 🍂 Juka Changes \n $(changelog) \n ## ⌨️ Juka IDE Changes \n $(MY_XT)"
    auth_token:
      secure: v/vwWedaFbZZt7xBtarpKXtoaub9EY/zbvwdUz9Yccsc0rykWiDaV1zYuMjDb8kn
    draft: false
    prerelease: false
    on:
      branch: main                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only